BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Transport" (
	"TransportID"		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SchafID"			INTEGER NOT NULL,
	"TransportMittel"	TEXT NOT NULL,
	"Grund"				TEXT
);
CREATE TABLE IF NOT EXISTS "Betriebsnummer" (
	"BetriebsID"		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SchafID"			INTEGER NOT NULL,
	"Betriebsnummer"	TEXT NOT NULL,
	"Bemerkung"			TEXT
);
CREATE TABLE IF NOT EXISTS "Gedeckt" (
	"GedecktID"		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SchafID"		INTEGER NOT NULL,
	"VaterKennung"	TEXT NOT NULL,
	"Datum"			TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Klauenschneiden" (
	"KlauenID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SchafID"	INTEGER NOT NULL,
	"Datum"		TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Impfungen" (
	"ImpfID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SchafID"	INTEGER NOT NULL,
	"Impfstoff"	TEXT NOT NULL,
	"Bemerkung"	TEXT,
	"Datum"		TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Entwurmen" (
	"EntwurmenID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SchafID"		INTEGER NOT NULL,
	"Datum"			TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Schur" (
	"SchurID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SchafID"	INTEGER NOT NULL,
	"Datum"		TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Schaf" (
	"SchafID"			INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"DatumZugang"		TEXT,
	"DatumAbgang"		TEXT,
	"GrundFürAbgang"	TEXT,
	"Kennung"			TEXT,
	"Bemerkung"			TEXT,
	"MutterKennung"		TEXT
);
COMMIT;
