/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.edv.bestandsregister.GUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.JMarsDarkTheme;
import mdlaf.themes.MaterialOceanicTheme;

/**
 *
 * @author Markus
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabPlane = new javax.swing.JTabbedPane();
        jTabImpfungen2 = new javax.swing.JPanel();
        jTabSchaf = new javax.swing.JPanel();
        jTabBetriebsnummer = new javax.swing.JPanel();
        jTabEntwurmen = new javax.swing.JPanel();
        jTabGedeckt = new javax.swing.JPanel();
        jTabImpfungen = new javax.swing.JPanel();
        jTabKlauenschneiden = new javax.swing.JPanel();
        jTabSchur = new javax.swing.JPanel();
        jTabTransport = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jTabImpfungen2Layout = new javax.swing.GroupLayout(jTabImpfungen2);
        jTabImpfungen2.setLayout(jTabImpfungen2Layout);
        jTabImpfungen2Layout.setHorizontalGroup(
            jTabImpfungen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabImpfungen2Layout.setVerticalGroup(
            jTabImpfungen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Impfungen", jTabImpfungen2);

        javax.swing.GroupLayout jTabSchafLayout = new javax.swing.GroupLayout(jTabSchaf);
        jTabSchaf.setLayout(jTabSchafLayout);
        jTabSchafLayout.setHorizontalGroup(
            jTabSchafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabSchafLayout.setVerticalGroup(
            jTabSchafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Schaf", jTabSchaf);

        javax.swing.GroupLayout jTabBetriebsnummerLayout = new javax.swing.GroupLayout(jTabBetriebsnummer);
        jTabBetriebsnummer.setLayout(jTabBetriebsnummerLayout);
        jTabBetriebsnummerLayout.setHorizontalGroup(
            jTabBetriebsnummerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabBetriebsnummerLayout.setVerticalGroup(
            jTabBetriebsnummerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Betriebsnummer", jTabBetriebsnummer);

        javax.swing.GroupLayout jTabEntwurmenLayout = new javax.swing.GroupLayout(jTabEntwurmen);
        jTabEntwurmen.setLayout(jTabEntwurmenLayout);
        jTabEntwurmenLayout.setHorizontalGroup(
            jTabEntwurmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabEntwurmenLayout.setVerticalGroup(
            jTabEntwurmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Entwurmen", jTabEntwurmen);

        javax.swing.GroupLayout jTabGedecktLayout = new javax.swing.GroupLayout(jTabGedeckt);
        jTabGedeckt.setLayout(jTabGedecktLayout);
        jTabGedecktLayout.setHorizontalGroup(
            jTabGedecktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabGedecktLayout.setVerticalGroup(
            jTabGedecktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Gedeckt", jTabGedeckt);

        javax.swing.GroupLayout jTabImpfungenLayout = new javax.swing.GroupLayout(jTabImpfungen);
        jTabImpfungen.setLayout(jTabImpfungenLayout);
        jTabImpfungenLayout.setHorizontalGroup(
            jTabImpfungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabImpfungenLayout.setVerticalGroup(
            jTabImpfungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Impfungen", jTabImpfungen);

        javax.swing.GroupLayout jTabKlauenschneidenLayout = new javax.swing.GroupLayout(jTabKlauenschneiden);
        jTabKlauenschneiden.setLayout(jTabKlauenschneidenLayout);
        jTabKlauenschneidenLayout.setHorizontalGroup(
            jTabKlauenschneidenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabKlauenschneidenLayout.setVerticalGroup(
            jTabKlauenschneidenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Klauenschneiden", jTabKlauenschneiden);

        javax.swing.GroupLayout jTabSchurLayout = new javax.swing.GroupLayout(jTabSchur);
        jTabSchur.setLayout(jTabSchurLayout);
        jTabSchurLayout.setHorizontalGroup(
            jTabSchurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabSchurLayout.setVerticalGroup(
            jTabSchurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Schur", jTabSchur);

        javax.swing.GroupLayout jTabTransportLayout = new javax.swing.GroupLayout(jTabTransport);
        jTabTransport.setLayout(jTabTransportLayout);
        jTabTransportLayout.setHorizontalGroup(
            jTabTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jTabTransportLayout.setVerticalGroup(
            jTabTransportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        jTabPlane.addTab("Transport", jTabTransport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTabPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabPlane.getAccessibleContext().setAccessibleName("Schaf");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //MaterialLookAndFeel.changeTheme(new MaterialOceanicTheme());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTabBetriebsnummer;
    private javax.swing.JPanel jTabEntwurmen;
    private javax.swing.JPanel jTabGedeckt;
    private javax.swing.JPanel jTabImpfungen;
    private javax.swing.JPanel jTabImpfungen2;
    private javax.swing.JPanel jTabKlauenschneiden;
    private javax.swing.JTabbedPane jTabPlane;
    private javax.swing.JPanel jTabSchaf;
    private javax.swing.JPanel jTabSchur;
    private javax.swing.JPanel jTabTransport;
    // End of variables declaration//GEN-END:variables
}
